repos:
  - repo: https://github.com/psf/black
    rev: 24.1.0
    hooks:
      - id: black

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.0
    hooks:
      - id: ruff

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
      - id: mypy


#  -   repo: local
#      hooks:
#        - id: pytest
#          name: pytest
#          entry: poetry run pytest
#          language: system
#          pass_filenames: false
